# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: nest main_test

on:
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Copy Example Config Directory
        run: |
          cp -r config.example config

      - name: Create Config Folder
        run: mkdir config

      - name: Create File
        run: |
          touch config/test.yml
          echo "ENV_VAR_NAME=example" >> $GITHUB_ENV

      - name: Set Environment Variables
        run: |
          echo "ENV_VAR_NAME=example" >> $GITHUB_ENV
          echo "ANOTHER_ENV_VAR=12345" >> $GITHUB_ENV

      - run: npm ci
      - run: npm run build --if-present # 이거까지 있어야 할까? 한 번 알아보자.
      - run: npm test
